spring:
  #datasource
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tutu0214
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#log
logging:
  level:
    root: info
    com.tutu.blog: debug
  file:
    path: log/blog-dev.log
    max-history: 30
server:
  port: 8888