
spring:
  #datasource
  datasource:
    url: jdbc:mysql://101.201.127.139:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tutu0214
  #jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#log
logging:
  level:
    root: warn
    com.tutu.blog: info
  file:
    path: log/blog-pro.log
server:
  port: 8088